# Generated by Django 2.2.6 on 2019-11-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0006_auto_20191106_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplerequest',
            name='report_num',
            field=models.IntegerField(db_column='REPORT_NUM', null=True),
        ),
    ]
