# Generated by Django 2.2.6 on 2019-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0007_auto_20191109_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplerequest',
            name='district_id',
            field=models.IntegerField(db_column='DISTRICT_ID', null=True),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='event_property_id',
            field=models.IntegerField(blank=True, db_column='EVENT_PROPERTY_ID', null=True),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='event_type_id',
            field=models.IntegerField(db_column='EVENT_TYPE_ID', null=True),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='intime_archive_num',
            field=models.IntegerField(db_column='INTIME_ARCHIVE_NUM', null=True),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='intime_to_archive_num',
            field=models.IntegerField(blank=True, db_column='INTIME_TO_ARCHIVE_NUM', null=True),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='operate_num',
            field=models.IntegerField(blank=True, db_column='OPERATE_NUM', null=True),
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='overtime_archive_num',
            field=models.IntegerField(blank=True, db_column='OVERTIME_ARCHIVE_NUM', null=True),
        ),
    ]
