# Generated by Django 2.2.6 on 2019-11-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0009_auto_20191109_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplerequest',
            options={'ordering': ('-id',)},
        ),
    ]
