# Generated by Django 2.2.7 on 2019-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0011_auto_20191113_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplerequest',
            options={},
        ),
        migrations.AlterField(
            model_name='peoplerequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
