# Generated by Django 2.2.7 on 2019-11-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
