# Generated by Django 2.2.7 on 2019-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0004_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsrProfile',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=20, null=True)),
                ('password', models.TextField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'UserProfile',
                'ordering': ('-id',),
            },
        ),
    ]
