# Generated by Django 2.2.7 on 2019-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_usrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrprofile',
            name='getindate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usrprofile',
            name='worknum',
            field=models.IntegerField(null=True),
        ),
    ]
