# Generated by Django 2.2.6 on 2019-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplerequest',
            name='report_num',
            field=models.IntegerField(blank=True, db_column='REPORT_NUM', null=True),
        ),
    ]
