# Generated by Django 2.2.7 on 2019-11-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0010_auto_20191110_1110'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peoplerequest',
            table='people_request_database',
        ),
    ]
